spring:
  rabbitmq:
    host: 192.168.127.22
    port: 5672
    username: guest
    password: guest
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true
#minio文件客户端配置
minio:
  endpoint: 192.168.10.100
  port: 9000
  accessKey:
  secretKey:
  secure: false
  bucketName:
  configDir:
